version: '3'
services:
  web:
    build: .
    ports:
     - "8000:8000"
    networks:
     - default
    volumes:
     - .:/code
    restart: always
  memcached:
    image: "memcached:1.4.36-alpine"
    ports:
     - "11211:11211"
    restart: always
